Tue Aug 29 11:02:22 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x03AB4710>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Tue Aug 29 11:18:28 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x034B0D70>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
Tue Aug 29 11:18:31 2017 | 	server error:HTTPConnectionPool(host='192.168.1.92', port=8004): Max retries exceeded with url: /api/date/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x034D5990>, 'Connection to 192.168.1.92 timed out. (connect timeout=1)'))
